//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerAdmin
    {
        public int Id { get; set; }
        public string Body { get; set; }
        public System.DateTime Date { get; set; }
        public int CommentID { get; set; }
    
        public virtual Comment Comment { get; set; }
    }
}
