//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListBlog.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class listblogEntities7 : DbContext
    {
        public listblogEntities7()
            : base("name=listblogEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<AnswerAdmin> AnswerAdmins { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<CategoryGallery> CategoryGalleries { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<Journal> Journals { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Poetry> Poetries { get; set; }
        public virtual DbSet<Section_articles> Section_articles { get; set; }
    }
}
